baseURL = "http://hugotest.bep.is"
title = "Hugo Test Site"
paginate = 2

disableHugoGeneratorInject = true
# hugo pygments support works only for native formats like markdown, not asciidoctor
# pygmentscodefences = "true"
# enables syntax guessing for code fences without specified language
# pygmentscodefencesguesssyntax = true
# # color-codes for highlighting derived from this style
# pygmentsstyle = "friendly"
# pygmentsstyle = "monokai"
[params]
	git_host = "https://github.com"
	# git_host = "https://gitlab.com"
	git_repo = "dreamcat4/hugotest"

	# hljs_style = "light"
	hljs_style = "dark"

	# highlightjs - light themes
	hljs_style_light = "gruvbox-light"
	# hljs_style_light = "kimbie.light"
	# hljs_style_light = "purebasic"
	# hljs_style_light = "solarized-light"

	# highlightjs - dark themes
	# hljs_style_dark = "atom-one-dark"
	hljs_style_dark = "gruvbox-dark"
	# hljs_style_dark = "hopscotch"
	# hljs_style_dark = "kimbie.dark"
	# hljs_style_dark = "ocean"
	# hljs_style_dark = "solarized-dark"
	# hljs_style_dark = "tomorrow-night-eighties"
	# hljs_style_dark = "zenburn"
