# baseURL = "http://127.0.0.1"
baseURL = "https://dreamcat4.github.io/hugotest/"

title = "Hugo Test Site"
paginate = 2

# defaultContentLanguage = "en" # this is the default
languageCode = "en-us"

# this is necessary to get .Date from the file modification time
useModTimeAsFallback = true

#  allows us to access Git revision information in theme files like author name, email, hash, and date
# this also needs to be implemented in the theme
enableGitInfo = true

# do not append 's' to the list.html pages
pluralizelisttitles = false

# removes <meta content="Hugo 0.23" name="generator">
disableHugoGeneratorInject = true

# append .html to urls instead of hiding it and appending /, requires restart
# uglyURLs = true

# if config.toml is in ./ then render the specified subfolder instead of hugo site files from ./
# source = "website/src"

# the folder to publish the website to
publishDir = "docs"

# delete all previous files before publishing
cleanDestinationDir = true

# launch $EDITOR after hugo new page
newContentEditor = "subl"

# hugo pygments support works only for native formats like markdown, not asciidoctor
# pygmentscodefences = "true"
# enables syntax guessing for code fences without specified language
# pygmentscodefencesguesssyntax = true
# # color-codes for highlighting derived from this style
# pygmentsstyle = "friendly"
# pygmentsstyle = "monokai"

# put here your site's google analytics id, it also needs to be implemented in the hugo theme
googleAnalytics = "UA-12345768-1"

# dont watch for changes on these files
# ignoreFiles: ["\\.png$", "\\.jpeg$"]

[params]
	# Wether to render the frontmatter .Title as an first <h1> in page .Content
	section_titles = true
	page_titles = true

	author = "Dreamcat4"
	author_url = "https://github.com/dreamcat4"


	# For 'Edit Source' and 'File Issue' buttons
	git_icons_with_text = false
	# git_icons_with_text = true

	git_host = "https://github.com"
	# git_host = "https://gitlab.com"
	git_repo = "dreamcat4/hugotest"

	# asciidoc themes from asciidoctor-stylesheet-factory
	# asciidoc_theme = "asciidoctor"
	asciidoc_theme = "colony"
	# asciidoc_theme = "foundation"
	# asciidoc_theme = "github"
	# asciidoc_theme = "golo"
	# asciidoc_theme = "readthedocs"
	# asciidoc_theme = "riak"
	# asciidoc_theme = "rocket-panda"
	# asciidoc_theme = "rubygems"


	# hljs_style = "light"
	hljs_style = "dark"

	# highlightjs - light themes
	hljs_style_light = "gruvbox-light"
	# hljs_style_light = "kimbie.light"
	# hljs_style_light = "purebasic"
	# hljs_style_light = "solarized-light"

	# highlightjs - dark themes
	# hljs_style_dark = "atom-one-dark"
	hljs_style_dark = "gruvbox-dark"
	# hljs_style_dark = "hopscotch"
	# hljs_style_dark = "kimbie.dark"
	# hljs_style_dark = "ocean"
	# hljs_style_dark = "solarized-dark"
	# hljs_style_dark = "tomorrow-night-eighties"
	# hljs_style_dark = "zenburn"
